import React from 'react';
import { Metadata } from 'next';
import Link from 'next/link';
import { ArrowLeft, ShieldCheck, Thermometer, CheckCircle2, AlertTriangle, Scale, FileText, Wrench } from 'lucide-react';
import { absoluteUrl, SITE_NAME } from '@/lib/site';
import { generateBreadcrumbSchema } from '@/lib/breadcrumbs';

export const metadata: Metadata = {
  title: 'Editorial Standards & Verification Protocol // Meal Instructions',
  description:
    'Our strict empirical testing standards, NIST-calibrated thermometry, USDA FSIS compliance, zero-hallucination policy, and physical recipe validation pipeline.',
  alternates: { canonical: absoluteUrl('/editorial-standards') },
};

export default function EditorialStandardsPage() {
  const breadcrumbs = generateBreadcrumbSchema([
    { name: 'Editorial Standards', path: '/editorial-standards' },
  ]);

  const articleSchema = {
    '@context': 'https://schema.org',
    '@type': 'Article',
    headline: 'Editorial Standards & Culinary Verification Protocol',
    description: 'Empirical testing methodologies, NIST-calibrated thermometry, and zero-hallucination policies governing Meal Instructions.',
    author: {
      '@type': 'Person',
      name: 'Alex Langton',
      jobTitle: 'Founder & Head of Kitchen Operations',
      url: absoluteUrl('/about'),
    },
    publisher: {
      '@type': 'Organization',
      name: SITE_NAME,
      url: absoluteUrl('/'),
      logo: absoluteUrl('/logo-512.png'),
    },
    mainEntityOfPage: absoluteUrl('/editorial-standards'),
  };

  const faqSchema = {
    '@context': 'https://schema.org',
    '@type': 'FAQPage',
    mainEntity: [
      {
        '@type': 'Question',
        name: 'Are recipes or cook times on Meal Instructions generated by AI algorithms?',
        acceptedAnswer: {
          '@type': 'Answer',
          text: 'No. Under Standing Rule HR-1, combinatorial programmatic generation of recipes by looping protein, flavor, and appliance arrays is strictly prohibited. Every recipe and cook-time datasheet is individually authored, mathematically modeled, and physically verified in our test kitchen.',
        },
      },
      {
        '@type': 'Question',
        name: 'How are temperature benchmarks calibrated for safety and culinary quality?',
        acceptedAnswer: {
          '@type': 'Answer',
          text: 'Temperatures are measured using NIST-traceable digital thermocouple thermometers (ThermoWorks Thermapen ONE) accurate to ±0.5°F (±0.3°C). All safe target thresholds are cross-referenced with USDA FSIS time-temperature pasteurization tables (7-log10 lethality curves).',
        },
      },
      {
        '@type': 'Question',
        name: 'Where does the nutritional data on Meal Instructions come from?',
        acceptedAnswer: {
          '@type': 'Answer',
          text: 'Nutritional metrics are never estimated by formulas or array indices. All macronutrient and micronutrient profiles are calculated directly from verified raw ingredient data in the USDA FoodData Central (FDC) SR Legacy and Foundation Foods databases, accounting for thermal moisture purge and lipid rendering.',
        },
      },
      {
        '@type': 'Question',
        name: 'What is the correction procedure if an error or temperature discrepancy is reported?',
        acceptedAnswer: {
          '@type': 'Answer',
          text: 'When a reader or laboratory tester submits a temperature or timing discrepancy via hello@mealinstructions.com, our test kitchen logs the report, replicates the cook on matching consumer hardware, and issues an immediate code update within 48 hours if variance is detected.',
        },
      },
    ],
  };

  return (
    <div className="max-w-4xl mx-auto px-4 sm:px-8 py-8 sm:py-16 space-y-12 text-ink font-sans">
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumbs) }}
      />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(articleSchema) }}
      />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }}
      />

      {/* Breadcrumb */}
      <div className="flex items-center justify-between text-xs font-mono text-ink-subtle">
        <Link
          href="/about"
          className="inline-flex items-center gap-1 hover:text-ink transition-colors uppercase"
        >
          <ArrowLeft className="w-3.5 h-3.5" />
          <span>Back to About</span>
        </Link>
        <span className="uppercase text-ink-muted">DOCUMENT // EDITORIAL INTEGRITY &amp; TESTING</span>
      </div>

      {/* Hero Header */}
      <header className="space-y-4 border-b border-ink pb-8">
        <div className="font-mono text-[11px] uppercase tracking-[0.14em] font-bold text-accent">
          E-E-A-T SCIENTIFIC PROTOCOL
        </div>
        <h1 className="text-3xl sm:text-5xl font-black tracking-tight text-ink uppercase font-sans">
          Editorial Standards &amp; Verification Protocol
        </h1>
        <p className="text-base sm:text-xl text-ink-muted leading-relaxed max-w-[55ch]">
          How we research, author, calibrate, and physically verify every recipe, parametric cook-time datasheet, and culinary calculation on this site.
        </p>
      </header>

      {/* Overview Card */}
      <section className="bg-paper-card p-6 border border-hairline space-y-4 font-mono text-xs">
        <div className="text-ink font-bold uppercase border-b border-hairline pb-2 flex items-center justify-between">
          <span>THE MEAL INSTRUCTIONS CORE COMMITMENT</span>
          <span className="text-accent">EST. 2024</span>
        </div>
        <p className="text-ink-muted font-sans text-sm leading-relaxed">
          The culinary internet is inundated with low-effort blog spam, algorithmically synthesized recipes with unverified cooking times, fabricated nutrition facts, and 2,000-word autobiographical stories designed solely for ad-network dwell time. Meal Instructions was founded on the opposite premise: <strong>ruthlessly verified, zero-fluff, engineering-grade culinary reference data for home cooks.</strong>
        </p>
      </section>

      {/* Pillar 1: Empirical Testing */}
      <section className="space-y-6">
        <div className="border-b border-hairline pb-3">
          <div className="font-mono text-[11px] uppercase tracking-[0.14em] font-bold text-accent">PILLAR 01</div>
          <h2 className="text-2xl sm:text-3xl font-bold uppercase tracking-tight text-ink">
            Empirical Test Kitchen Verification
          </h2>
        </div>

        <div className="space-y-4 text-sm text-ink-muted leading-relaxed font-sans">
          <p>
            No recipe or cook-time datasheet is ever published based on theoretical estimates or cookbook hearsay. Every timing benchmark is established through hands-on cooking in our dedicated residential test facility using standard consumer hardware:
          </p>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-4 font-mono text-xs text-ink pt-2">
            <div className="p-4 bg-paper-card border border-hairline space-y-2">
              <div className="font-bold text-accent uppercase flex items-center gap-1.5">
                <Thermometer className="w-4 h-4" />
                <span>NIST-Calibrated Thermometry</span>
              </div>
              <p className="font-sans text-xs text-ink-muted leading-relaxed">
                All internal meat core temperatures and convective chamber air temperatures are logged using <strong>ThermoWorks Thermapen ONE</strong> digital thermocouples and <strong>ThermoWorks Smoke</strong> multi-channel transmitters with ±0.5°F (±0.3°C) certified factory NIST accuracy. Thermometers are recalibrated annually via physical ice-point bath verification (32.0°F / 0.0°C).
              </p>
            </div>

            <div className="p-4 bg-paper-card border border-hairline space-y-2">
              <div className="font-bold text-accent uppercase flex items-center gap-1.5">
                <Wrench className="w-4 h-4" />
                <span>Standardized Consumer Hardware</span>
              </div>
              <p className="font-sans text-xs text-ink-muted leading-relaxed">
                Testing is conducted on retail consumer appliances (Breville Smart Oven Air Fryer Pro, Lodge 12-inch Cast Iron Skillets, Weber 22-inch Kettle Grills, Instant Pot Duo 6-qt, and standard residential electric/gas ranges) running on standard 120V line voltage, not commercial salamanders or industrial combi-ovens.
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* Pillar 2: USDA FSIS Microbiological Lethality */}
      <section className="space-y-6">
        <div className="border-b border-hairline pb-3">
          <div className="font-mono text-[11px] uppercase tracking-[0.14em] font-bold text-accent">PILLAR 02</div>
          <h2 className="text-2xl sm:text-3xl font-bold uppercase tracking-tight text-ink">
            USDA FSIS Microbial Lethality Compliance
          </h2>
        </div>

        <div className="space-y-4 text-sm text-ink-muted leading-relaxed font-sans">
          <p>
            Food safety is non-negotiable. All doneness recommendations and internal pull temperatures on Meal Instructions are mathematically harmonized with the <strong>USDA Food Safety and Inspection Service (FSIS) Pasteurization Lethality Tables</strong> (7-log10 reduction for Salmonella in poultry; 6.5-log10 reduction in beef).
          </p>
          <div className="p-4 bg-paper-card border border-hairline space-y-2 font-mono text-xs">
            <div className="font-bold text-ink uppercase text-[11px]">
              Dwell Time vs Instantaneous Pasteurization
            </div>
            <p className="font-sans text-xs text-ink-muted leading-relaxed">
              While the USDA consumer guideline mandates 165°F (73.9°C) instantaneous pasteurization for poultry, FSIS Appendix A lethality kinetics confirm that holding chicken at <strong>155°F (68.3°C) for 44.2 seconds</strong> achieves the identical 7.0-log10 pathogen reduction. Our datasheets specify both the chef-standard pull temperature (factoring in 5°F–8°F carryover resting rise) and the instantaneous USDA safe threshold so home cooks achieve tender, juicy meat without sacrificing food safety.
            </p>
          </div>
        </div>
      </section>

      {/* Pillar 3: Zero-Hallucination Covenant */}
      <section className="space-y-6">
        <div className="border-b border-hairline pb-3">
          <div className="font-mono text-[11px] uppercase tracking-[0.14em] font-bold text-accent">PILLAR 03</div>
          <h2 className="text-2xl sm:text-3xl font-bold uppercase tracking-tight text-ink">
            The Zero-Hallucination &amp; Data Integrity Covenant
          </h2>
        </div>

        <div className="space-y-4 text-sm text-ink-muted leading-relaxed font-sans">
          <p>
            Our repository operates under hard engineering constraints documented in our standing rules (<code className="font-mono text-xs bg-paper-card px-1 py-0.5 border border-hairline">AGENTS.md</code>):
          </p>

          <ul className="space-y-3 font-sans text-xs text-ink-muted">
            <li className="flex items-start gap-2.5 p-3 bg-paper-card border border-hairline">
              <CheckCircle2 className="w-4 h-4 text-emerald-700 shrink-0 mt-0.5" />
              <span><strong>HR-1: Ban on Combinatorial Generation.</strong> Scripts that mechanically generate recipes by looping <code className="font-mono">protein × flavor × appliance</code> are permanently banned. Every recipe is individually authored and culinary-reviewed.</span>
            </li>
            <li className="flex items-start gap-2.5 p-3 bg-paper-card border border-hairline">
              <CheckCircle2 className="w-4 h-4 text-emerald-700 shrink-0 mt-0.5" />
              <span><strong>HR-2: No Fabricated Numbers.</strong> Cook times, temperatures, and nutritional data may never be derived from array indices or arbitrary random formulas. Every nutrition object links to USDA FDC data; every cook time links to an empirical hardware test basis.</span>
            </li>
            <li className="flex items-start gap-2.5 p-3 bg-paper-card border border-hairline">
              <CheckCircle2 className="w-4 h-4 text-emerald-700 shrink-0 mt-0.5" />
              <span><strong>HR-3: Physical Validity Gate.</strong> Every protein × appliance combination must be physically valid in real life. No automated absurdity like &ldquo;Slow Cooker Parmesan Herb Crusted Tenders&rdquo; or &ldquo;Air Fryer Cottage Cheese.&rdquo;</span>
            </li>
            <li className="flex items-start gap-2.5 p-3 bg-paper-card border border-hairline">
              <CheckCircle2 className="w-4 h-4 text-emerald-700 shrink-0 mt-0.5" />
              <span><strong>HR-4: Anti-Duplicate Prose Audit.</strong> Content commits must pass an automated cryptographic prose audit (<code className="font-mono">npm run audit:content</code>) verifying that taglines, pro tips, reheat notes, and step descriptions are 100% unique per page.</span>
            </li>
          </ul>
        </div>
      </section>

      {/* Pillar 4: Corrections & Reader Feedback */}
      <section className="space-y-6">
        <div className="border-b border-hairline pb-3">
          <div className="font-mono text-[11px] uppercase tracking-[0.14em] font-bold text-accent">PILLAR 04</div>
          <h2 className="text-2xl sm:text-3xl font-bold uppercase tracking-tight text-ink">
            Corrections &amp; Continuous Calibration
          </h2>
        </div>

        <div className="space-y-4 text-sm text-ink-muted leading-relaxed font-sans">
          <p>
            No culinary dataset is static. Variations in meat water content, appliance age, regional altitude, and line voltage can influence cooking outcomes. We maintain an open, proactive corrections channel:
          </p>
          <div className="p-4 bg-paper-card border border-hairline space-y-2">
            <div className="font-bold text-ink uppercase text-xs font-mono">
              The 48-Hour Replication Protocol
            </div>
            <p className="text-xs text-ink-muted font-sans leading-relaxed">
              If a reader reports an inconsistent result or timing anomaly, our test kitchen replicates the cook within 48 hours using the reader&apos;s exact hardware model and cut thickness. If variance exceeds our ±10% margin of error, the datasheet is adjusted immediately with a public revision timestamp.
            </p>
            <div className="pt-2">
              <Link
                href="/contact"
                className="font-mono text-xs text-accent underline uppercase font-bold"
              >
                Submit a Correction or Temperature Report →
              </Link>
            </div>
          </div>
        </div>
      </section>

      {/* On-Page FAQs */}
      <section className="bg-paper hairline-border p-6 sm:p-8 space-y-6">
        <div className="border-b border-hairline pb-3">
          <div className="micro-label text-accent font-mono">FREQUENTLY ASKED QUESTIONS</div>
          <h2 className="text-xl font-bold uppercase text-ink font-sans">
            Editorial Policies &amp; Methodological Transparency
          </h2>
        </div>

        <div className="space-y-6">
          {faqSchema.mainEntity.map((faq, i) => (
            <div key={i} className="space-y-2">
              <h3 className="text-sm font-bold uppercase text-ink font-sans flex items-baseline gap-2">
                <span className="text-accent font-mono text-xs">0{i + 1}.</span>
                {faq.name}
              </h3>
              <p className="text-xs text-ink-muted leading-relaxed font-sans pl-5">
                {faq.acceptedAnswer.text}
              </p>
            </div>
          ))}
        </div>
      </section>

      {/* Colophon & Links */}
      <footer className="pt-6 border-t border-hairline flex flex-wrap items-center justify-between gap-4 font-mono text-xs text-ink-muted">
        <div>Published by Meal Instructions Test Kitchen Operations</div>
        <div className="flex gap-4">
          <Link href="/about" className="hover:text-ink transition-colors uppercase">About Us</Link>
          <Link href="/test-kitchen" className="hover:text-ink transition-colors uppercase">Hardware Lab</Link>
          <Link href="/contact" className="hover:text-ink transition-colors uppercase">Contact</Link>
        </div>
      </footer>
    </div>
  );
}
