// Recipe page — recreation of app/recipes/[slug]/RecipeClientView.tsx
(() => {
const { Lean5SMatrix, ModeSwitch, ShareButton, PortionScaler, MealActions, Button, Pill, Icon, LeanIcon, Panel, MicroLabel } = window.MealInstructionsDesignSystem_767cb5;
const rmono = { fontFamily:'var(--font-mono)' };
const fmt = (s) => String(Math.floor(s / 60)).padStart(2, '0') + ':' + String(s % 60).padStart(2, '0');
function scale(q, m) { const v = q * m; return Number.isInteger(v) ? String(v) : (Math.round(v * 100) / 100).toString(); }
function RecipeScreen({ D, slug, go }) {
  const r = D.recipes.find((x) => x.slug === slug) || D.recipes[0];
  const [mode, setMode] = React.useState('fast'); const [mult, setMult] = React.useState(4); const [done, setDone] = React.useState([]);
  const secs0 = ((r.quickVersion && r.quickVersion.timerMinutes) || r.cookMinutes || 12) * 60;
  const [left, setLeft] = React.useState(secs0); const [run, setRun] = React.useState(false); const [fin, setFin] = React.useState(false);
  React.useEffect(() => { if (!run || left <= 0) return; const t = setInterval(() => setLeft((p) => { if (p <= 1) { setRun(false); setFin(true); return 0; } return p - 1; }), 1000); return () => clearInterval(t); }, [run, left]);
  const ds = D.datasheets.find((d) => d.relatedRecipeSlug === r.slug);
  const related = D.recipes.filter((x) => x.slug !== r.slug && (x.appliance === r.appliance || x.protein === r.protein)).slice(0, 4);
  const qv = r.quickVersion || { bullets:[r.tagline], timerMinutes:r.cookMinutes || 12, flipAtMinutes:0 };
  const steps = r.detailedSteps || [];
  const ings = r.ingredients || [];
  const head = { display:'flex', alignItems:'center', justifyContent:'space-between', borderBottom:'1px solid var(--hairline)', paddingBottom:16 };
  const H2 = ({ children }) => <h2 style={{ margin:0, fontFamily:'var(--font-sans)', fontSize:20, fontWeight:700, textTransform:'uppercase', letterSpacing:'-.01em', color:'var(--ink)' }}>{children}</h2>;
  return (
    <div style={{ maxWidth:896, margin:'0 auto', padding:'32px 32px', display:'flex', flexDirection:'column', gap:32 }}>
      <div style={{ display:'flex', alignItems:'center', justifyContent:'space-between', fontSize:12, ...rmono, color:'var(--ink-subtle)' }}>
        <a href="#" onClick={(e) => { e.preventDefault(); go('home'); }} className="mi-hover-ink" style={{ display:'inline-flex', alignItems:'center', gap:4, textTransform:'uppercase', color:'inherit' }}><Icon name="arrow-left" size={14} /><span>Back to Index</span></a>
        <div style={{ display:'flex', gap:8 }}><span>SPECIMEN #{r.id}</span><span>•</span><span style={{ textTransform:'uppercase', color:'var(--ink-muted)' }}>{r.appliance}</span></div>
      </div>
      <Panel padding="xl" as="section" style={{ display:'flex', flexDirection:'column', gap:24 }}>
        <div style={{ display:'flex', flexWrap:'wrap', gap:8 }}><Pill bold>{r.appliance}</Pill>{(r.categories || []).map((c) => <Pill key={c} variant="muted" href="#" onClick={(e) => e.preventDefault()}>{c}</Pill>)}<Pill variant="verified">VERIFIED NO-FLUFF</Pill></div>
        <div style={{ display:'flex', flexDirection:'column', gap:8 }}><h1 style={{ margin:0, fontFamily:'var(--font-sans)', fontSize:36, fontWeight:700, letterSpacing:'-.01em', textTransform:'uppercase', color:'var(--ink)', lineHeight:1.25 }}>{r.title}</h1><p style={{ margin:0, fontSize:16, color:'var(--ink-muted)', lineHeight:1.625 }}>{r.tagline}</p></div>
        <div style={{ display:'flex', flexWrap:'wrap', alignItems:'center', gap:'4px 12px', fontSize:11, ...rmono, textTransform:'uppercase', letterSpacing:'.08em', color:'var(--ink-muted)' }}><span>By <a href="#" className="mi-opacity-link" style={{ color:'var(--ink)', textDecoration:'underline' }}>Meal Instructions Kitchen</a></span><span style={{ color:'var(--ink-subtle)' }}>•</span><span>Published {r.datePublished || 'Aug 29, 2026'}</span><span style={{ color:'var(--ink-subtle)' }}>•</span><span style={{ color:'var(--verified-strong)' }}>Reviewed for USDA Food Safety</span></div>
        {r.image && <div className="hairline-border" style={{ position:'relative', width:'100%', height:384, borderRadius:4, overflow:'hidden', background:'var(--paper)' }}><img src={r.image} alt={r.title} style={{ width:'100%', height:'100%', objectFit:'cover', display:'block' }} /></div>}
        <Lean5SMatrix cookTemp={r.cookTemp} totalMinutes={r.totalMinutes} proteinGrams={(r.nutrition && r.nutrition.proteinGrams) || 30} flipMinutes={qv.flipAtMinutes} servings={r.defaultServings || 4} />
        <ShareButton smsText={'🍳 ' + r.title.toUpperCase()} markdown={'# ' + r.title} />
      </Panel>
      {ds && <Panel verified hover as="a" href="#" onClick={(e) => { e.preventDefault(); go('datasheet', ds.slug); }} padding="lg" style={{ display:'flex', flexDirection:'column', gap:16, textDecoration:'none', color:'inherit' }}>
        <div style={{ display:'flex', alignItems:'center', justifyContent:'space-between', gap:8, flexWrap:'wrap' }}><div style={{ display:'flex', alignItems:'center', gap:8 }}><Icon name="shield-check" size={16} style={{ color:'var(--verified)' }} /><span style={{ ...rmono, fontSize:10, fontWeight:700, textTransform:'uppercase', letterSpacing:'.08em', color:'var(--verified-strong)' }}>Verified Cook-Time Datasheet</span>{ds.state !== 'fresh' && <Pill variant="info" size="xs">{ds.state}</Pill>}</div><span className="mi-hover-accent" style={{ display:'flex', alignItems:'center', gap:4, ...rmono, fontSize:10, color:'var(--ink-muted)', textTransform:'uppercase' }}>View Full Datasheet <Icon name="arrow-up-right" size={12} /></span></div>
        <div><h3 style={{ margin:0, fontSize:14, fontWeight:700, textTransform:'uppercase', letterSpacing:'-.01em', color:'var(--ink)' }}>{ds.food}</h3><p style={{ margin:'2px 0 0', fontSize:12, color:'var(--ink-muted)' }}>{ds.cutOrPrep}</p></div>
        <div style={{ display:'grid', gridTemplateColumns:'repeat(5, minmax(0,1fr))', gap:8 }}>{[[ds.tempF + '°F', 'Temp'], [ds.timeFormatted, 'Cook Time'], [ds.internalTempTargetF ? ds.internalTempTargetF + '°F' : '—', 'Internal', true], ds.flipAtMinutes > 0 && [ds.flipAtMinutes + 'm', 'Flip At'], ds.restMinutes > 0 && [ds.restMinutes + 'm', 'Rest']].filter(Boolean).map(([v, l, a]) => <div key={l} className="hairline-border" style={{ background:'var(--paper)', padding:10, textAlign:'center' }}><div style={{ ...rmono, fontSize:18, fontWeight:700, color: a ? 'var(--accent)' : 'var(--ink)' }}>{v}</div><div style={{ fontSize:9, ...rmono, color:'var(--ink-subtle)', textTransform:'uppercase', marginTop:2 }}>{l}</div></div>)}</div>
        <div className="hairline-border" style={{ fontSize:12, color:'var(--ink-muted)', background:'var(--paper)', padding:12, lineHeight:1.625 }}><span style={{ ...rmono, fontSize:10, fontWeight:700, color:'var(--ink)', textTransform:'uppercase' }}>Doneness: </span>{ds.donenessCue}</div>
        <div style={{ ...rmono, fontSize:10, color:'var(--ink-subtle)', borderTop:'1px solid var(--hairline)', paddingTop:8 }}>{ds.verificationBasis}</div>
      </Panel>}
      <div style={{ display:'flex', flexDirection:'column', gap:32 }}>
        <ModeSwitch mode={mode} onChange={setMode} top={64} />
        <Panel as="section" padding="lg" style={{ display:'flex', flexDirection:'column', gap:16 }}>
          <div style={{ display:'flex', flexWrap:'wrap', alignItems:'center', justifyContent:'space-between', gap:16 }}>
            <div style={{ display:'flex', alignItems:'center', gap:12 }}><div className="hairline-border" style={{ width:32, height:32, background:'var(--paper)', display:'flex', alignItems:'center', justifyContent:'center', color:'var(--accent)' }}><Icon name="clock" size={16} /></div><div><h3 style={{ margin:0, fontWeight:700, fontSize:14, textTransform:'uppercase', color:'var(--ink)' }}>{r.appliance} Timer</h3><p style={{ margin:0, fontSize:12, color:'var(--ink-muted)' }}>Set for {qv.timerMinutes} mins @ {r.cookTemp}{qv.flipAtMinutes ? ' (Flip at ' + qv.flipAtMinutes + 'm)' : ''}</p></div></div>
            <div style={{ display:'flex', alignItems:'center', gap:16 }}><div className={fin ? 'animate-bounce' : ''} style={{ ...rmono, fontSize:30, fontWeight:700, letterSpacing:'-.01em', color: fin ? 'var(--accent)' : run ? 'var(--ink)' : 'var(--ink-muted)' }}>{fmt(left)}</div><div style={{ display:'flex', gap:6 }}><Button variant={run ? 'caution' : fin ? 'accent' : 'ink'} icon={run ? 'pause' : 'play'} onClick={() => { if (fin) { setLeft(secs0); setFin(false); setRun(true); } else setRun(!run); }} style={{ padding:'8px 16px' }}>{run ? 'PAUSE' : fin ? 'DONE!' : 'START'}</Button><Button variant="outline-muted" iconOnly icon="rotate-ccw" title="Reset timer" onClick={() => { setRun(false); setFin(false); setLeft(secs0); }} /></div></div>
          </div>
        </Panel>
        <Panel as="section" padding="xl" style={{ display:'flex', flexDirection:'column', gap:24 }}>
          <div style={{ ...head, flexWrap:'wrap', gap:16 }}><div style={{ display:'flex', alignItems:'center', gap:12 }}><div className="hairline-border" style={{ padding:8, background:'var(--paper)', display:'flex' }}><LeanIcon name="fork-knife" size={24} /></div><div><H2>Ingredients</H2><p style={{ margin:0, fontSize:12, color:'var(--ink-muted)' }}>Base recipe calibrated for {r.defaultServings || 4} adults.</p></div></div><PortionScaler variant="multiplier" currentServings={mult} onChange={setMult} /></div>
          <div style={{ display:'grid', gridTemplateColumns:'1fr 1fr', gap:12, fontSize:14 }}>{ings.map((i, k) => <div key={k} className="hairline-border" style={{ display:'flex', alignItems:'flex-start', gap:12, padding:12, background:'var(--paper)' }}><span className="hairline-border" style={{ ...rmono, fontSize:12, fontWeight:700, color:'var(--ink)', background:'var(--paper-50)', padding:'2px 8px', flexShrink:0 }}>{i.qtyNumeric ? scale(i.qtyNumeric, mult / 4) + ' ' + i.unit : i.qty + ' ' + i.unit}</span><div style={{ fontSize:14, color:'var(--ink)', lineHeight:1.375 }}><span style={{ fontWeight:700 }}>{i.item}</span>{i.notes && <span style={{ color:'var(--ink-muted)', display:'block', fontSize:12, marginTop:2 }}>{i.notes}</span>}</div></div>)}</div>
        </Panel>
        <div style={{ display:'flex', flexDirection:'column', gap:24 }}>
          {mode === 'fast' && <Panel as="section" padding="xl" style={{ display:'flex', flexDirection:'column', gap:24 }}>
            <div style={head}><div style={{ display:'flex', alignItems:'center', gap:8 }}><Icon name="zap" size={20} style={{ color:'var(--accent)' }} /><H2>Get to the Point Execution</H2></div><span style={{ ...rmono, fontSize:10, color:'var(--ink-subtle)', textTransform:'uppercase' }}>20-WORD BULLETS // NO FLUFF</span></div>
            <div style={{ display:'flex', flexDirection:'column', gap:16 }}>{qv.bullets.map((b, i) => <div key={i} className="hairline-border" style={{ display:'flex', alignItems:'flex-start', gap:16, padding:16, background:'var(--paper)', fontSize:14 }}><span style={{ width:24, height:24, borderRadius:'50%', background:'var(--ink)', color:'var(--paper)', display:'flex', alignItems:'center', justifyContent:'center', ...rmono, fontSize:12, fontWeight:700, flexShrink:0, marginTop:2 }}>{i + 1}</span><p style={{ margin:0, color:'var(--ink)', fontWeight:500, lineHeight:1.625 }}>{b}</p></div>)}</div>
            {qv.flipAtMinutes > 0 && <div className="hairline-border" style={{ padding:12, background:'var(--paper)', ...rmono, fontSize:12, display:'flex', alignItems:'center', gap:10 }}><div className="hairline-border" style={{ padding:4, background:'var(--paper-50)', color:'var(--accent)', display:'flex' }}><LeanIcon name="flip-action" size={18} /></div><span style={{ fontWeight:700, textTransform:'uppercase', color:'var(--accent)' }}>Critical Flip Mark:</span><span>Flip at exactly <strong>{qv.flipAtMinutes} minutes</strong>.</span></div>}
          </Panel>}
          {mode === 'detailed' && <Panel as="section" padding="xl" style={{ display:'flex', flexDirection:'column', gap:24 }}>
            <div style={head}><div style={{ display:'flex', alignItems:'center', gap:8 }}><Icon name="book-open" size={20} /><H2>Step-by-Step Guided Instructions</H2></div><span style={{ ...rmono, fontSize:10, color:'var(--ink-subtle)', textTransform:'uppercase' }}>FLUFF-FREE GUIDED STEPS</span></div>
            <div style={{ display:'flex', flexDirection:'column', gap:24 }}>{steps.map((s) => { const isDone = done.includes(s.stepNumber); return <div key={s.stepNumber} onClick={() => setDone(isDone ? done.filter((n) => n !== s.stepNumber) : [...done, s.stepNumber])} className={'mi-step' + (isDone ? ' is-done' : '')} style={{ display:'flex', flexDirection:'column', gap:12 }}>
              <div style={{ display:'flex', alignItems:'center', justifyContent:'space-between', ...rmono, fontSize:12 }}><div style={{ display:'flex', alignItems:'center', gap:8 }}><span style={{ width:20, height:20, display:'flex', alignItems:'center', justifyContent:'center', borderRadius:4, fontSize:10, fontWeight:700, background: isDone ? 'var(--verified-check)' : 'var(--ink)', color:'#fff' }}>{isDone ? '✓' : s.stepNumber}</span><span style={{ fontWeight:700, fontSize:14, color:'var(--ink)', fontFamily:'var(--font-sans)', textTransform:'uppercase' }}>{s.title}</span></div>{s.timerMinutes && <span style={{ color:'var(--ink-subtle)', textTransform:'uppercase' }}>⏱️ {s.timerMinutes} MINS</span>}</div>
              <p style={{ margin:0, fontSize:14, lineHeight:1.625, color: isDone ? 'var(--ink-muted)' : 'var(--ink)', textDecoration: isDone ? 'line-through' : 'none' }}>{s.instruction}</p>
              {s.proTip && <div className="hairline-border" style={{ background:'var(--paper-50)', padding:12, fontSize:12, color:'var(--ink-muted)' }}><span style={{ ...rmono, fontWeight:700, color:'var(--ink)', textTransform:'uppercase', fontSize:10, display:'block' }}>💡 Dad Pro Tip:</span><p style={{ margin:0, fontSize:12 }}>{s.proTip}</p></div>}
            </div>; })}{!steps.length && <p style={{ margin:0, fontSize:12, color:'var(--ink-subtle)', ...rmono }}>Detailed steps not included in this sample record.</p>}</div>
          </Panel>}
        </div>
      </div>
      <section style={{ display:'grid', gridTemplateColumns:'1fr 1fr', gap:24, ...rmono, fontSize:12 }}>
        <Panel padding="lg" style={{ display:'flex', flexDirection:'column', gap:16 }}><div style={{ display:'flex', alignItems:'center', gap:8, color:'var(--ink)', fontWeight:700, textTransform:'uppercase', borderBottom:'1px solid var(--hairline)', paddingBottom:8 }}><Icon name="shield-check" size={16} style={{ color:'var(--verified)' }} /><span>Dad Pro Tip</span></div><p style={{ margin:0, fontFamily:'var(--font-sans)', fontSize:12, color:'var(--ink)', lineHeight:1.625 }}>{r.dadProTip || r.tagline}</p>{r.kidAdjustment && <div style={{ paddingTop:8, borderTop:'1px solid var(--hairline)' }}><span style={{ fontSize:10, color:'var(--ink-subtle)', textTransform:'uppercase', display:'block', fontWeight:700 }}>👶 Kid &amp; Toddler Adjustment:</span><p style={{ margin:'4px 0 0', fontFamily:'var(--font-sans)', fontSize:12, color:'var(--ink-muted)', lineHeight:1.625 }}>{r.kidAdjustment}</p></div>}</Panel>
        <Panel padding="lg" style={{ display:'flex', flexDirection:'column', gap:16 }}><div style={{ display:'flex', alignItems:'center', gap:8, color:'var(--ink)', fontWeight:700, textTransform:'uppercase', borderBottom:'1px solid var(--hairline)', paddingBottom:8 }}><Icon name="flame" size={16} style={{ color:'var(--accent)' }} /><span>Serve With &amp; Reheating</span></div><div><span style={{ fontSize:10, color:'var(--ink-subtle)', textTransform:'uppercase', display:'block', fontWeight:700 }}>Suggested Sides:</span><ul style={{ margin:'4px 0 0', paddingLeft:16, fontFamily:'var(--font-sans)', fontSize:12, color:'var(--ink)' }}>{(r.sideSuggestions || ['—']).map((s) => <li key={s}>{s}</li>)}</ul></div><div style={{ paddingTop:8, borderTop:'1px solid var(--hairline)' }}><span style={{ fontSize:10, color:'var(--ink-subtle)', textTransform:'uppercase', display:'block', fontWeight:700 }}>🔥 Reheat Method (Restore Crunch):</span><p style={{ margin:'4px 0 0', fontFamily:'var(--font-sans)', fontSize:12, color:'var(--ink-muted)', lineHeight:1.625 }}>{r.reheatInstructions || '—'}</p></div></Panel>
      </section>
      <Panel as="section" padding="lg" style={{ ...rmono, fontSize:12, color:'var(--ink)', display:'flex', flexDirection:'column', gap:8 }}>
        <div style={{ display:'flex', justifyContent:'space-between', alignItems:'center', borderBottom:'1px solid var(--hairline)', paddingBottom:8 }}><span style={{ fontWeight:700, textTransform:'uppercase' }}>Nutrition &amp; Verification Basis</span><span style={{ color:'var(--ink-subtle)' }}>HR-2 SOURCED</span></div>
        {r.nutrition && <div style={{ display:'grid', gridTemplateColumns:'repeat(4, 1fr)', gap:16, padding:'8px 0' }}><div>Calories: <strong>{r.nutrition.calories || '—'} kcal</strong></div><div>Protein: <strong>{r.nutrition.proteinGrams}g</strong></div><div>Carbohydrates: <strong>{r.nutrition.carbsGrams || '—'}g</strong></div><div>Fat: <strong>{r.nutrition.fatGrams || '—'}g</strong></div></div>}
        <div style={{ fontSize:11, color:'var(--ink-muted)', borderTop:'1px solid var(--hairline)', paddingTop:8, fontFamily:'var(--font-sans)', display:'flex', flexDirection:'column', gap:4 }}>{r.nutrition && r.nutrition.source && <div><strong>Nutrition Source:</strong> {r.nutrition.source}</div>}<div><strong>Cook Time Basis:</strong> {r.basis || 'See datasheet.'}</div></div>
      </Panel>
      <MealActions recipeTitle={r.title} signedIn={false} style={{ marginTop:0 }} />
      {related.length > 0 && <section style={{ display:'flex', flexDirection:'column', gap:16, paddingTop:24, borderTop:'1px solid var(--hairline)' }}>
        <h3 style={{ margin:0, fontSize:16, fontWeight:700, textTransform:'uppercase', letterSpacing:'-.01em', color:'var(--ink)' }}>Related {r.appliance.replace('-', ' ')} Recipes</h3>
        <div style={{ display:'grid', gridTemplateColumns:'repeat(4, minmax(0,1fr))', gap:16 }}>{related.map((x) => <a key={x.id} href="#" onClick={(e) => { e.preventDefault(); go('recipe', x.slug); }} className="mi-tile"><div style={{ display:'flex', flexDirection:'column', gap:8 }}><span style={{ ...rmono, fontSize:10, fontWeight:700, color:'var(--ink-subtle)' }}>#{x.id}</span><h4 className="mi-tile__title" style={{ margin:0, fontWeight:700, fontSize:12, color:'var(--ink)' }}>{x.title}</h4></div><div style={{ borderTop:'1px solid var(--hairline)', marginTop:12, paddingTop:8, ...rmono, fontSize:10, color:'var(--ink-muted)', display:'flex', justifyContent:'space-between' }}><span>{x.cookTemp}</span><span>{x.totalMinutes}m</span></div></a>)}</div>
      </section>}
    </div>);
}
window.RecipeScreen = RecipeScreen;
})();
