/**
 * Prices every matched ingredient at one Kroger store and writes
 * `data/ingredient-prices.generated.json`.
 *
 *   KROGER_CLIENT_ID=… KROGER_CLIENT_SECRET=… \
 *   KROGER_PRICE_LOCATION_ID=01400513 npx tsx scripts/build-ingredient-prices.ts
 *
 * Reads the productIds already resolved in `data/kroger-matches.generated.json`
 * — matching and pricing are separate jobs, because matches are stable and
 * prices are not. Re-run this whenever prices should be refreshed; there is no
 * need to re-run the matcher.
 *
 * HR-2: every row written carries the store it was priced at and the timestamp
 * it was read. An ingredient the store does not carry is written with NO price
 * rather than a fallback, so `npm run report:cost` counts it as a gap instead
 * of the site quoting a number nobody can pay.
 */

import fs from 'node:fs';
import path from 'node:path';
import { fetchProductPrices } from '../lib/kroger/client';
import { canonicalIngredient } from '../lib/ingredient-cost';

const LOCATION = process.env.KROGER_PRICE_LOCATION_ID ?? process.env.KROGER_BUILD_LOCATION_ID;
if (!LOCATION) {
  console.error(
    'Set KROGER_PRICE_LOCATION_ID (a Kroger store id). Without a store Kroger\n' +
      'returns products with no price at all — see lib/kroger/client.ts.\n' +
      'Find one with: npx tsx scripts/kroger-match-report.ts',
  );
  process.exit(1);
}

const root = process.cwd();
const OUT = path.join(root, 'data/ingredient-prices.generated.json');
const matches = JSON.parse(
  fs.readFileSync(path.join(root, 'data/kroger-matches.generated.json'), 'utf8'),
).ingredients as Record<string, { productId: string; size?: string; description?: string }[]>;

/** One product per canonical ingredient — the best-scoring match wins. */
const wanted = new Map<string, { productId: string; raw: string }>();
for (const [raw, list] of Object.entries(matches)) {
  if (!list?.length) continue;
  const key = canonicalIngredient(raw);
  if (!wanted.has(key)) wanted.set(key, { productId: list[0].productId, raw });
}

const ids = [...wanted.values()].map((v) => v.productId);
console.log(`pricing ${ids.length} products for ${wanted.size} ingredients at store ${LOCATION}`);

const CHUNK = 50; // Kroger's cap on filter.productId
const priceById = new Map<string, { regular: number; promo?: number; size?: string }>();

for (let i = 0; i < ids.length; i += CHUNK) {
  const batch = ids.slice(i, i + CHUNK);
  const priced = await fetchProductPrices(batch, LOCATION);
  for (const p of priced) priceById.set(p.productId, { regular: p.regular, promo: p.promo, size: p.size });
  console.log(`  ${Math.min(i + CHUNK, ids.length)}/${ids.length} — ${priceById.size} priced so far`);
}

const fetchedAt = new Date().toISOString();
const out: Record<string, unknown> = {};
let missing = 0;

for (const [key, { productId, raw }] of wanted) {
  const p = priceById.get(productId);
  if (!p) {
    missing += 1;
    continue;
  }
  out[key] = {
    packagePrice: p.promo ?? p.regular,
    packageSize: p.size ?? matches[raw]?.[0]?.size ?? '',
    source: `Kroger store ${LOCATION}, product ${productId}${p.promo ? ' (promo price)' : ''}`,
    fetchedAt,
  };
}

fs.writeFileSync(
  OUT,
  JSON.stringify(
    {
      generatedAt: fetchedAt,
      locationId: LOCATION,
      note:
        'Generated by scripts/build-ingredient-prices.ts. Do not hand-edit. An ' +
        'ingredient absent from `prices` was not carried or not priced at this ' +
        'store — that is deliberate, and report:cost counts it as a gap.',
      prices: out,
    },
    null,
    2,
  ) + '\n',
);

console.log(`\nwrote ${Object.keys(out).length} prices to data/ingredient-prices.generated.json`);
console.log(`${missing} ingredients had a match but no price at this store`);
