/**
 * Resolves every unique recipe ingredient to Kroger productIds, once, at build
 * time — writing data/kroger-matches.generated.json.
 *
 * Resolution runs against one reference store rather than no store at all.
 * For most groceries the results are identical either way — same products,
 * same productIds, only price and availability differ. But restricted
 * categories are location-gated: without a locationId, "red wine" returns
 * nothing but vinegar, and the cache silently shipped Red Wine Vinegar for a
 * pot roast. A reference store makes those categories visible, and the
 * productIds it yields are the same ones every other store uses.
 *
 * Store-specific price and availability are still deliberately not cached —
 * those are resolved live, per shopper, at cart time.
 *
 * Incremental by default: ingredients already present in the output are
 * skipped, so a rerun after adding recipes only resolves the new ones.
 *
 *   npx tsx --env-file=.env.local scripts/build-kroger-matches.ts [--force]
 */

import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { matchIngredient } from '../lib/kroger/client';

const OUT = new URL('../data/kroger-matches.generated.json', import.meta.url);
const FORCE = process.argv.includes('--force');
/** Re-attempt cached abstentions — use after improving the matcher. */
const RETRY_ABSTAINED = process.argv.includes('--retry-abstained');
/** Reference store used only to make location-gated categories visible. */
const BUILD_LOCATION_ID = process.env.KROGER_BUILD_LOCATION_ID ?? '01400513';

interface CachedMatch {
  productId: string;
  description: string;
  category?: string;
  brand?: string;
  size?: string;
  matchedQuery: string;
  score: number;
}

interface Cache {
  generatedAt: string;
  note: string;
  /** ingredient string → resolved products (empty array means a real abstention) */
  ingredients: Record<string, CachedMatch[]>;
}

async function main() {
  const raw = JSON.parse(readFileSync(new URL('../data/recipes.json', import.meta.url), 'utf8'));
  const recipes = Array.isArray(raw) ? raw : raw.recipes;
  const unique = [...new Set(recipes.flatMap((r: any) => r.ingredients.map((i: any) => i.item)))] as string[];

  const cache: Cache = !FORCE && existsSync(OUT)
    ? JSON.parse(readFileSync(OUT, 'utf8'))
    : { generatedAt: '', note: '', ingredients: {} };

  const todo = unique.filter(
    (i) =>
      FORCE ||
      !(i in cache.ingredients) ||
      (RETRY_ABSTAINED && cache.ingredients[i].length === 0),
  );
  console.log(`${unique.length} unique ingredients; ${todo.length} to resolve` + (todo.length ? '' : ' (nothing to do)'));

  let resolved = 0;
  let abstained = 0;
  let failed = 0;

  for (const [n, item] of todo.entries()) {
    try {
      const result = await matchIngredient(item, BUILD_LOCATION_ID);
      cache.ingredients[item] = result.matches.map((m) => ({
        productId: m.productId,
        description: m.description,
        category: m.categories?.[0],
        brand: m.brand,
        size: m.size,
        matchedQuery: m.matchedQuery,
        score: m.score,
      }));
      if (result.matches.length) resolved++;
      else abstained++;
    } catch (e) {
      // Leave it out of the cache entirely rather than recording a false
      // abstention — a later run will retry it.
      failed++;
      console.error(`  ! ${item}: ${(e as Error).message.slice(0, 90)}`);
    }

    if ((n + 1) % 25 === 0) {
      console.log(`  ${n + 1}/${todo.length}  resolved=${resolved} abstained=${abstained} failed=${failed}`);
      // Checkpoint, so a long run is never lost to a crash near the end.
      flush(cache);
    }
  }

  flush(cache);
  const total = Object.keys(cache.ingredients).length;
  console.log(`\nresolved=${resolved} abstained=${abstained} failed=${failed}`);
  console.log(`cache now covers ${total}/${unique.length} ingredients -> data/kroger-matches.generated.json`);
}

function flush(cache: Cache) {
  cache.generatedAt = new Date().toISOString();
  cache.note = 'Generated by scripts/build-kroger-matches.ts. Do not hand-edit. '
    + 'An empty array means no confident match was found — that is deliberate, '
    + 'not a gap to fill in by hand.';
  writeFileSync(OUT, JSON.stringify(cache, null, 2) + '\n');
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
