// Sample data for cards + UI kit. Values are copied from the live mealinstructions.com home page (2026-09-05) — recipe cards, HUD datasheet CT-AF-004, category and crisis counts. Datasheets other than CT-AF-004 reuse the matching recipe's published temp/time (marked source:'recipe-card') — they are placeholders, not the cook-time DB.
window.MI_DATA = (function(){
  var ROOT = (function(){ var s = (document.currentScript && document.currentScript.getAttribute('src')) || ''; return s.replace(/components\/sample-data\.js.*$/, ''); })();
  var IMG = ROOT + 'assets/images/recipes/';
  var recipes = [
    { id:'0001', slug:'crispy-air-fryer-chicken-tenders', title:'Crispy Air Fryer Chicken Tenders', tagline:'Golden panko crunch outside, juicy inside in 10 minutes with zero hot oil splatter.', protein:'chicken', appliance:'air-fryer', cookTemp:'400°F (204°C)', cookTempF:400, totalMinutes:15, prepMinutes:5, cookMinutes:10, difficulty:'Dead Simple', nutrition:{ proteinGrams:42, calories:350, carbsGrams:20, fatGrams:10, source:'USDA FoodData Central #171077' }, categories:['kid-approved','15-minute','high-protein'], image: IMG+'air-fryer-crispy-chicken-tenders.jpg', defaultServings:4, safeInternalTempF:165, restMinutes:2, basis:'Tested in 6-qt basket air fryer at 400°F (204°C) with 1.5-inch raw chicken tenderloins. USDA FSIS 165°F target.', datePublished:'2026-08-29',
      quickVersion:{ timerMinutes:12, flipAtMinutes:6, bullets:['Set up three bowls: flour with garlic powder, beaten eggs, and panko mixed with parmesan and smoked paprika.','Pat 1.5 lbs chicken tenders dry. Dredge in flour, dip in egg, then press into panko mixture.','Arrange in a single layer in a greased air fryer basket. Spray tops with cooking spray.','Air fry at 400°F for 12 minutes, flipping at 6 minutes, until golden and internal temp hits 165°F.'] },
      detailedSteps:[{ stepNumber:1, title:'Set Up the Breading Station', instruction:'Set up three shallow bowls. Bowl 1: 1/2 cup all-purpose flour mixed with 1/2 tsp garlic powder. Bowl 2: 2 beaten eggs. Bowl 3: 1.5 cups panko breadcrumbs mixed with 1/4 cup grated parmesan cheese, 1/2 tsp smoked paprika, 1/2 tsp salt, and 1/4 tsp black pepper.', proTip:'Adding parmesan to the panko creates an extra layer of savory flavor and helps the crust brown more evenly in the air fryer.' },{ stepNumber:2, title:'Bread the Chicken', instruction:'Pat 1.5 lbs chicken tenderloins completely dry with paper towels. Working one at a time, dredge each tender in the seasoned flour, shaking off excess. Dip into beaten egg, letting excess drip off. Press firmly into the panko-parmesan mixture, coating all sides.', proTip:'Use one hand for the dry ingredients and the other for the wet. This prevents your fingers from getting caked with breading that falls off in clumps.' },{ stepNumber:3, title:'Air Fry', instruction:'Spray the air fryer basket with cooking spray. Arrange breaded tenders in a single layer with space between each piece. Spray the tops of the tenders lightly with cooking spray. Air fry at 400°F (204°C) for 12 minutes, flipping halfway at 6 minutes.', proTip:'Do not stack or overlap the tenders. Air needs to circulate around each piece for even crisping. Cook in batches if needed.', timerMinutes:12 },{ stepNumber:4, title:'Check and Rest', instruction:'Confirm internal temperature reaches 165°F using an instant-read thermometer inserted into the thickest part. Transfer to a wire rack and rest for 2 minutes before serving with your favorite dipping sauces.', proTip:'Resting on a wire rack instead of a plate prevents the bottom from getting soggy from trapped steam.', timerMinutes:2 }],
      ingredients:[{ item:'Chicken Tenderloins', qty:'1.5', qtyNumeric:1.5, unit:'lbs' },{ item:'Panko Breadcrumbs', qty:'1.5', qtyNumeric:1.5, unit:'cups' },{ item:'Parmesan Cheese', qty:'1/4', qtyNumeric:.25, unit:'cup', notes:'grated' },{ item:'Large Eggs', qty:'2', qtyNumeric:2, unit:'pieces', notes:'beaten' },{ item:'All-Purpose Flour', qty:'1/2', qtyNumeric:.5, unit:'cup' },{ item:'Garlic Powder', qty:'1/2', qtyNumeric:.5, unit:'tsp' },{ item:'Smoked Paprika', qty:'1/2', qtyNumeric:.5, unit:'tsp' },{ item:'Kosher Salt', qty:'1/2', qtyNumeric:.5, unit:'tsp' },{ item:'Black Pepper', qty:'1/4', qtyNumeric:.25, unit:'tsp' },{ item:'Cooking Spray', qty:'1', qtyNumeric:1, unit:'can' }],
      dadProTip:'These taste like restaurant chicken tenders but with a fraction of the oil and none of the deep fryer cleanup. The parmesan in the panko is the secret weapon for next-level crunch.', kidAdjustment:'Serve with a lineup of dipping sauces: honey mustard, ketchup, BBQ sauce, and ranch. Let kids pick their favorites and dip away.', sideSuggestions:['Air fryer french fries','Steamed broccoli with cheese','Apple slices with caramel dip'], reheatInstructions:'Reheat in the air fryer at 360°F for 3-4 minutes until crispy again. Never microwave or the breading will turn soft and rubbery.' },
    { id:'0002', slug:'air-fryer-juicy-bacon-cheeseburgers', title:'Air Fryer Juicy Bacon Cheeseburgers', tagline:'Diner-grade sear and steakhouse juiciness in 10 minutes with zero stove splatter.', protein:'beef', appliance:'air-fryer', cookTemp:'375°F (190°C)', cookTempF:375, totalMinutes:15, difficulty:'Dead Simple', nutrition:{ proteinGrams:44 }, categories:['kid-approved','15-minute','high-protein'], image: IMG+'air-fryer-juicy-bacon-cheeseburgers.jpg' },
    { id:'0003', slug:'air-fryer-10-minute-garlic-butter-salmon', title:'10-Minute Garlic Butter Air Fryer Salmon', tagline:'Buttery, flaky salmon with crispy skin and garlic herb crust in under 10 minutes.', protein:'seafood', appliance:'air-fryer', cookTemp:'400°F (204°C)', cookTempF:400, totalMinutes:11, difficulty:'Dead Simple', nutrition:{ proteinGrams:38 }, categories:['15-minute','high-protein','five-ingredient'], image: IMG+'air-fryer-10-minute-garlic-butter-salmon.jpg' },
    { id:'0004', slug:'cast-iron-lacy-edge-smash-burgers', title:'Cast-Iron Lacy-Edge Smash Burgers', tagline:'Ultra-crispy caramelized edges, double American cheese, and secret burger sauce in 5 minutes.', protein:'beef', appliance:'cast-iron', cookTemp:'Smoking Hot', cookTempF:500, totalMinutes:10, difficulty:'Easy', nutrition:{ proteinGrams:42 }, categories:['15-minute','game-day','kid-approved'], image: IMG+'cast-iron-lacy-edge-smash-burgers.jpg' },
    { id:'0005', slug:'sheet-pan-chicken-fajitas', title:'Sheet Pan Sizzling Chicken Fajitas', tagline:'Tender spiced chicken breast, sweet bell peppers, and charred onions on one single pan.', protein:'chicken', appliance:'sheet-pan', cookTemp:'425°F (218°C)', cookTempF:425, totalMinutes:23, difficulty:'Dead Simple', nutrition:{ proteinGrams:42 }, categories:['one-pan','high-protein','kid-approved'], image: IMG+'sheet-pan-chicken-fajitas.jpg' },
    { id:'0006', slug:'air-fryer-crispy-garlic-parm-wings', title:'Air Fryer Crispy Garlic Parmesan Wings', tagline:'Deep-fry crunch without hot oil, tossed in melted garlic butter and aged parmesan.', protein:'chicken', appliance:'air-fryer', cookTemp:'380°F (193°C)', cookTempF:380, totalMinutes:25, difficulty:'Easy', nutrition:{ proteinGrams:36 }, categories:['game-day','high-protein'], image: IMG+'air-fryer-crispy-garlic-parm-wings.jpg' },
    { id:'0007', slug:'15-minute-skillet-beef-taco-meat', title:'15-Minute Skillet Ground Beef Taco Meat', tagline:'Juicy, seasoned ground beef from scratch in 12 minutes. Zero packet filler or starch sludge.', protein:'beef', appliance:'skillet', cookTemp:'Medium-High', cookTempF:0, totalMinutes:12, difficulty:'Dead Simple', nutrition:{ proteinGrams:34 }, categories:['15-minute','budget','kid-approved'] },
    { id:'0008', slug:'air-fryer-sirloin-steak-bites', title:'Air Fryer Garlic Butter Sirloin Steak Bites', tagline:'Tender, juicy seared steak cubes dripping in melted herb butter in just 7 minutes.', protein:'beef', appliance:'air-fryer', cookTemp:'400°F (204°C)', cookTempF:400, totalMinutes:12, difficulty:'Dead Simple', nutrition:{ proteinGrams:42 }, categories:['15-minute','high-protein','five-ingredient'] },
    { id:'0009', slug:'sheet-pan-smoked-sausage-peppers-potatoes', title:'Sheet Pan Smoked Sausage, Peppers & Crispy Potatoes', tagline:'Savory sliced sausage, blistered bell peppers, and golden potato cubes with zero scrubbing.', protein:'pork', appliance:'sheet-pan', cookTemp:'400°F (204°C)', cookTempF:400, totalMinutes:35, difficulty:'Dead Simple', nutrition:{ proteinGrams:20 }, categories:['one-pan','budget'] },
    { id:'0010', slug:'cast-iron-butter-basted-ribeye', title:'Cast Iron Butter-Basted Ribeye Steak', tagline:'Restaurant-quality steakhouse sear with garlic herb butter pan basting in 8 minutes.', protein:'beef', appliance:'cast-iron', cookTemp:'Smoking Hot', cookTempF:500, totalMinutes:18, difficulty:'Easy', nutrition:{ proteinGrams:52 }, categories:['high-protein','five-ingredient','weekend'] },
    { id:'0011', slug:'air-fryer-crispy-parmesan-pork-chops', title:'Air Fryer Crispy Parmesan Crusted Pork Chops', tagline:'Juicy bone-in pork chops with a golden garlic parmesan crust in 12 minutes.', protein:'pork', appliance:'air-fryer', cookTemp:'380°F (193°C)', cookTempF:380, totalMinutes:17, difficulty:'Dead Simple', nutrition:{ proteinGrams:44 }, categories:['high-protein','kid-approved'] },
    { id:'0012', slug:'15-minute-lemon-garlic-butter-shrimp', title:'15-Minute Skillet Lemon Garlic Butter Shrimp', tagline:'Sweet jumbo shrimp seared in foaming garlic herb butter with fresh lemon in 6 minutes.', protein:'seafood', appliance:'skillet', cookTemp:'Medium-High', cookTempF:0, totalMinutes:11, difficulty:'Dead Simple', nutrition:{ proteinGrams:35 }, categories:['15-minute','high-protein','five-ingredient'] }
  ];
  var datasheets = [
    { id:'CT-AF-004', slug:'air-fryer-chicken-breast-boneless', foodSlug:'chicken-breast-boneless', food:'Chicken Breast (Boneless, Skinless)', appliance:'air-fryer', state:'fresh', cutOrPrep:'6–8 oz breasts, pounded to even 3/4-inch thickness', tempF:380, tempC:193, tempFormatted:'380°F (193°C)', timeFormatted:'12–15 mins', timeMinMinutes:12, timeMaxMinutes:15, flipAtMinutes:7, internalTempTargetF:165, internalTempTargetFormatted:'165°F (74°C)', restMinutes:5, oilSprayRequired:true, donenessCue:'Firm to touch, clear juices, instant read probe at 165°F.', verificationBasis:'Cosori Pro II Technical Guide; USDA FSIS 165°F standard.', proTip:'Pound to an even thickness so the thin end does not dry out before the thick end hits 165°F.', relatedRecipeSlug:'crispy-air-fryer-chicken-tenders', source:'live-hud' },
    { id:'CT-AF-—', slug:'air-fryer-salmon-fillets-fresh', foodSlug:'salmon-fillets-fresh', food:'Salmon Fillets', appliance:'air-fryer', state:'fresh', cutOrPrep:'Placeholder — values from recipe #0003 card', tempF:400, tempC:204, tempFormatted:'400°F (204°C)', timeFormatted:'11 mins', timeMinMinutes:8, timeMaxMinutes:11, flipAtMinutes:0, internalTempTargetF:145, internalTempTargetFormatted:'145°F (63°C)', restMinutes:2, oilSprayRequired:true, donenessCue:'Flakes easily with a fork; opaque center.', verificationBasis:'Placeholder from recipe card — replace with datasheet record.', relatedRecipeSlug:'air-fryer-10-minute-garlic-butter-salmon', source:'recipe-card' },
    { id:'CT-AF-—', slug:'air-fryer-beef-burger-patties-frozen', foodSlug:'beef-burger-patties-frozen', food:'Frozen Burger Patties', appliance:'air-fryer', state:'frozen', cutOrPrep:'Placeholder — values from recipe #0002 card', tempF:375, tempC:190, tempFormatted:'375°F (190°C)', timeFormatted:'15 mins', timeMinMinutes:12, timeMaxMinutes:15, flipAtMinutes:7, internalTempTargetF:160, internalTempTargetFormatted:'160°F (71°C)', restMinutes:2, oilSprayRequired:false, donenessCue:'No pink, juices run clear, probe reads 160°F.', verificationBasis:'Placeholder from recipe card — replace with datasheet record.', relatedRecipeSlug:'air-fryer-juicy-bacon-cheeseburgers', source:'recipe-card' },
    { id:'CT-AF-—', slug:'air-fryer-bacon-thick-cut', foodSlug:'bacon-thick-cut', food:'Thick-Cut Bacon', appliance:'air-fryer', state:'fresh', cutOrPrep:'Placeholder — values from recipe #0024 card', tempF:375, tempC:190, tempFormatted:'375°F (190°C)', timeFormatted:'9–10 mins', timeMinMinutes:9, timeMaxMinutes:10, flipAtMinutes:5, internalTempTargetF:0, internalTempTargetFormatted:'', restMinutes:1, oilSprayRequired:false, donenessCue:'Deep mahogany, fat fully rendered, edges crisp.', verificationBasis:'Placeholder from recipe card — replace with datasheet record.', relatedRecipeSlug:'air-fryer-bacon-no-splatter', source:'recipe-card' },
    { id:'CT-AF-—', slug:'air-fryer-pork-chops-bone-in', foodSlug:'pork-chops-bone-in', food:'Pork Chops (Bone-In)', appliance:'air-fryer', state:'fresh', cutOrPrep:'Placeholder — values from recipe #0011 card', tempF:380, tempC:193, tempFormatted:'380°F (193°C)', timeFormatted:'12 mins', timeMinMinutes:10, timeMaxMinutes:12, flipAtMinutes:6, internalTempTargetF:145, internalTempTargetFormatted:'145°F (63°C)', restMinutes:3, oilSprayRequired:true, donenessCue:'Probe reads 145°F at the bone; juices slightly pink.', verificationBasis:'Placeholder from recipe card — replace with datasheet record.', relatedRecipeSlug:'air-fryer-crispy-parmesan-pork-chops', source:'recipe-card' },
    { id:'CT-AF-—', slug:'air-fryer-sirloin-steak-bites', foodSlug:'sirloin-steak-bites', food:'Sirloin Steak Bites', appliance:'air-fryer', state:'fresh', cutOrPrep:'Placeholder — values from recipe #0008 card', tempF:400, tempC:204, tempFormatted:'400°F (204°C)', timeFormatted:'7 mins', timeMinMinutes:6, timeMaxMinutes:7, flipAtMinutes:4, internalTempTargetF:135, internalTempTargetFormatted:'135°F (57°C) medium-rare', restMinutes:3, oilSprayRequired:false, donenessCue:'Deep brown crust, warm red center.', verificationBasis:'Placeholder from recipe card — replace with datasheet record.', relatedRecipeSlug:'air-fryer-sirloin-steak-bites', source:'recipe-card' },
    { id:'CT-AF-—', slug:'air-fryer-chicken-wings-fresh', foodSlug:'chicken-wings-fresh', food:'Chicken Wings', appliance:'air-fryer', state:'fresh', cutOrPrep:'Placeholder — values from recipe #0006 card', tempF:380, tempC:193, tempFormatted:'380°F (193°C)', timeFormatted:'25 mins', timeMinMinutes:22, timeMaxMinutes:25, flipAtMinutes:12, internalTempTargetF:175, internalTempTargetFormatted:'175°F (79°C)', restMinutes:2, oilSprayRequired:false, donenessCue:'Skin blistered and crisp; probe at 175°F near the bone.', verificationBasis:'Placeholder from recipe card — replace with datasheet record.', relatedRecipeSlug:'air-fryer-crispy-garlic-parm-wings', source:'recipe-card' },
    { id:'CT-AF-—', slug:'air-fryer-frozen-french-fries', foodSlug:'frozen-french-fries', food:'Frozen French Fries', appliance:'air-fryer', state:'frozen', cutOrPrep:'Placeholder — values from recipe #0021 card', tempF:400, tempC:204, tempFormatted:'400°F (204°C)', timeFormatted:'13 mins', timeMinMinutes:12, timeMaxMinutes:13, flipAtMinutes:6, internalTempTargetF:0, internalTempTargetFormatted:'', restMinutes:0, oilSprayRequired:false, donenessCue:'Golden and rigid; shake basket at the flip mark.', verificationBasis:'Placeholder from recipe card — replace with datasheet record.', relatedRecipeSlug:'air-fryer-frozen-chicken-nuggets-and-fries', source:'recipe-card' }
  ];
  var presets = [['Chicken Breast','air-fryer-chicken-breast-boneless'],['Salmon Fillets','air-fryer-salmon-fillets-fresh'],['Frozen Burgers','air-fryer-beef-burger-patties-frozen'],['Thick Bacon','air-fryer-bacon-thick-cut'],['Pork Chops','air-fryer-pork-chops-bone-in'],['Steak Bites','air-fryer-sirloin-steak-bites'],['Chicken Wings','air-fryer-chicken-wings-fresh'],['Frozen Fries','air-fryer-frozen-french-fries']].map(function(p){ return { label:p[0], slug:p[1] }; });
  var CIMG = ROOT + 'assets/images/categories/';
  var categories = [
    { slug:'15-minute', name:'15-Minute Meals', heroTag:'SUB-15 MINUTE EXECUTION', image: CIMG+'15-minute-skillet.jpg', count:67 },
    { slug:'high-protein', name:'High Protein / Lean', heroTag:'30G+ PROTEIN PER SERVING', image: ROOT+'assets/images/hero/smash-burger.jpg', count:123 },
    { slug:'kid-approved', name:'Kid & Toddler Approved', heroTag:'UNANIMOUS TABLE APPROVAL', image: CIMG+'kid-approved-nuggets.jpg', count:86 },
    { slug:'budget', name:'Budget & Pantry Staples', heroTag:'UNDER $12 FAMILY MEAL', image: IMG+'sheet-pan-chicken-fajitas.jpg', count:68 },
    { slug:'no-thaw', name:'No-Thaw / From Frozen', heroTag:'ZERO DEFROST REQUIRED', image: IMG+'air-fryer-10-minute-garlic-butter-salmon.jpg', count:6 },
    { slug:'one-pan', name:'One-Pan & Sheet Pan', heroTag:'SINGLE VESSEL CLEANUP', image: ROOT+'assets/images/hero/air-fryer-tenders.jpg', count:55 },
    { slug:'five-ingredient', name:'Five-Ingredient Staples', heroTag:'5 INGREDIENTS OR FEWER', image: IMG+'cast-iron-lacy-edge-smash-burgers.jpg', count:36 },
    { slug:'sides', name:'Rapid Sides & Veggies', heroTag:'UNDER 10-MIN SIDES', count:19 },
    { slug:'snacks', name:'Late Night Snacks', heroTag:'INSTANT LATE NIGHT BITES', count:8 },
    { slug:'game-day', name:'Game Day & Finger Foods', heroTag:'CROWD-FEEDING APPETIZERS', image: IMG+'air-fryer-crispy-garlic-parm-wings.jpg', count:23 },
    { slug:'breakfast', name:'Dad Weekend Breakfast', heroTag:'WEEKEND GRIDDLE CLASSICS', count:19 },
    { slug:'weekend', name:'Weekend Project Cooks', heroTag:'RELAXED WEEKEND MASTERY', image: IMG+'air-fryer-juicy-bacon-cheeseburgers.jpg', count:66 }
  ];
  var proteinCounts = { chicken:51, beef:41, pork:38, seafood:23, turkey:12, lamb:2, vegetarian:37, 'dairy-eggs':22 };
  var crisisCounts = { 'no-thaw':6, 'sub-15':56, 'picky-kids':86, 'one-pan':55, 'high-protein':123, budget:68 };
  var appliances = ['Air Fryer','Standard Home Oven','Instant Pot / Pressure Cooker','12-Inch Skillet / Non-Stick','Sheet Pan (Convection Bake)','Cast Iron Skillet','Gas or Charcoal Grill','Dutch Oven / Heavy Pot','Slow Cooker / Crockpot','Pellet or Charcoal Smoker','Stovetop Boiling'];
  var guides = [
    { ref:'REF-01 // FAMILY LOGISTICS', title:'10 Things I Wish I Knew Before Cooking For A Family', desc:'Timeline synchronizing, heat moderation, and why pan crowding boils meat.', slug:'things-i-wish-i-knew-cooking-for-family' },
    { ref:'REF-02 // PICKY EATERS', title:'10 Rules for Getting Picky Kids to Eat Real Food', desc:'Deconstruction plating, dip leverage, and ending short-order cooking.', slug:'rules-picky-kids-eat-real-food' },
    { ref:'REF-03 // HARDWARE', title:'10 Cast Iron Mistakes Dads Make (And What Matters)', desc:'Debunking the soap myth, preheating duration, and dry meat searing.', slug:'cast-iron-mistakes-dads-make' },
    { ref:'REF-04 // CONVECTION', title:'10 Air Fryer Realities Nobody Puts in the Manual', desc:'Stopping white smoke, single-layer airflow, and -25°F conversion math.', slug:'air-fryer-realities-nobody-tells-you' }
  ];
  var fieldGuides = [
    { badge:'FOOD SCIENCE', title:'Why Wet Steaks Never Brown (Maillard Physics)', desc:'Water absorbs 2,260 J/g to vaporize. Stop steaming steaks at 212°F.', slug:'maillard-reaction-steak-searing', readMinutes:6 },
    { badge:'HARDWARE PHYSICS', title:'Air Fryer Convection & Boundary Layers', desc:'How 2,000 RPM airflow strips the boundary layer to cook 20% faster.', slug:'air-fryer-convection-airflow-physics', readMinutes:5 },
    { badge:'SALT DENSITY', title:'Equilibrium Salting (Diamond vs Morton)', desc:'Why a spoon of Morton salt is 70% saltier than Diamond Crystal.', slug:'equilibrium-salting-diamond-vs-morton', readMinutes:4 },
    { badge:'FOOD SAFETY', title:'USDA vs Chef Internal Temperatures', desc:'Why chicken is safe at 155°F with dwell time vs 165°F rubber.', slug:'safe-internal-meat-temperatures-guide', readMinutes:5 }
  ];
  var tools = [
    { href:'/reheat', badge:'CRISP REVIVE', title:'Takeout Revive Engine', description:'Restore fries, pizza, and tenders to crispness without microwave mush.', icon:'heat-waves', category:'emergency' },
    { href:'/frozen-cook', badge:'USDA SAFETY', title:'Freezer-to-Plate Matrix', description:'Forgot to thaw? Direct frozen cook times and cold-water speed thaw rules.', icon:'safety-shield', category:'emergency' },
    { href:'/dinner-sync', badge:'REVERSE TIMELINE', title:'Dinner Sync Scheduler', description:'Sync multiple appliances so protein, veggies, and carbs finish hot together.', icon:'clock', category:'planning' },
    { href:'/meat-math', badge:'COSTCO SCALER', title:'Feed The Crew Meat Math', description:'Calculate raw butcher weights accounting for 25-50% shrinkage and bones.', icon:'scale-weight', category:'ratios' },
    { href:'/internal-temp', badge:'CARRYOVER RISE', title:'Thermometer Pull Guide', description:'Exact temperatures to pull meat early to prevent dry overcooked steaks.', icon:'thermometer-probe', category:'temperature' },
    { href:'/salt-math', badge:'SALT DENSITY', title:'Equilibrium Salt Math', description:'Convert Diamond Crystal vs Morton salt accurately by weight and spoons.', icon:'scale-weight', category:'ratios' },
    { href:'/kid-split', badge:'ZERO DOUBLE-COOK', title:'Picky Kid Deconstructor', description:'60-second pull-aside steps to satisfy toddler sensory preferences.', icon:'portion-plate', category:'planning' },
    { href:'/troubleshoot', badge:'5-SEC FIXES', title:'Fix My Cook // Rescue', description:'Instant remedies for smoking air fryers, soggy fries, and gray steak.', icon:'flame', category:'emergency' },
    { href:'/air-fryer-calculator', badge:'CONVECTION MATH', title:'Air Fryer Conversion Calculator', description:'Convert any oven recipe: -25°F and -20% time, with basket-load adjustments.', icon:'appliance-air-fryer', category:'temperature' }
  ];
  var searchItems = recipes.map(function(r){ return { type:'recipe', id:r.id, title:r.title, subtitle:r.tagline, badge:r.appliance, time:r.totalMinutes+'m', href:'#/recipes/'+r.slug, keywords:[r.protein] }; })
    .concat(fieldGuides.map(function(g,i){ return { type:'guide', id:'G'+(i+1), title:g.title, subtitle:g.desc, badge:'FIELD GUIDE', time:g.readMinutes+'m read', href:'#/blog/'+g.slug }; }))
    .concat([{ type:'storage', id:'S1', title:'Cooked Chicken', subtitle:'Fridge: 3–4 days', badge:'STORAGE', time:'3–4 days', href:'#/storage/cooked-chicken' }]);
  return { root:ROOT, recipes:recipes, datasheets:datasheets, presets:presets, categories:categories, proteinCounts:proteinCounts, crisisCounts:crisisCounts, appliances:appliances, guides:guides, fieldGuides:fieldGuides, tools:tools, searchItems:searchItems, recipeCount:228, datasheetCount:378 };
})();
